alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
name: seraphin
region: tor
services:
  - build_command: npm run build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: svandegar/seraphin
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    name: seraphin
    routes:
      - path: /
    run_command: npm start
    source_dir: /
