alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
name: aynils
region: tor
services:
  - build_command: npm run export
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: aynils/aynils
    name: aynils
    routes:
      - path: /
    source_dir: /
